name: catcher
description: Package for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.7.1
homepage: https://github.com/thealteria/catcher

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^8.2.2
  dio: ^5.1.1
  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
