name: catcher
description: Package for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.7.1
homepage: https://github.com/thealteria/catcher

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  device_info_plus: ^9.0.3
  dio: ^5.1.1
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
