name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.7.0
homepage: https://github.com/thealteria/catcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  device_info_plus: ^8.2.2
  package_info_plus: ^3.0.0
  mailer: ^6.0.1
  dio: ^5.1.1
  flutter_mailer: ^2.0.0
  logging: ^1.0.2
  sentry: ^7.5.0
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
